#!/bin/bash

printf -v day "%02g" $2
folder="day$day"
case $1 in
  make)
    cp -R template $folder
    ;;
  test)
    haxe -C $folder --main "Test$3" -cp ../ --interp --library utest
    ;;
  run)
    haxe -C $folder --main "Solution$3" -cp ../ --interp
    ;;
  *)
    echo "Input command not recognized"
esac